# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven deploy for master

on:
  push:
    branches: [ dev ]
#  release:
#    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt
          cache: "maven"
      - name: Publish to GitHub Packages Maven
        run: >-
          export APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)-snapshot-$(date +%Y%m%d);
          mvn clean deploy -DskipTests=true -T 2C -DrepositoryId=github -Dversion=${APP_VERSION}
