# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven deploy for main

on:
  #  push:
  #    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt
          cache: "maven"
      - name: Publish to GitHub Packages Maven
        run: >-
          mvn clean deploy -DskipTests=true -T 2C -q
        env:
          GITHUB_TOKEN: ${{ github.token }}
# docker run --rm -v $(pwd):/repo --workdir /repo rhysd/actionlint:latest -color
# https://rhysd.github.io/actionlint/
